[theme]
base="light"
primaryColor="#2563eb"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f6f8fa"
textColor="#111827"
font="sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
